import {MigrationInterface, QueryRunner} from "typeorm";

export class initdb1616554310853 implements MigrationInterface {
    name = 'initdb1616554310853'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "genotype-disease-temp-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "geneSeq" character varying NOT NULL, "phenotype" character varying NOT NULL, "language" character varying NOT NULL, "genotypeDiseaseTempId" uuid, CONSTRAINT "PK_24f3b328545529ea6239010bf67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-disease-temp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "diseaseTempId" uuid, CONSTRAINT "PK_054e1ad1fc3e0c38213c03c6d01" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-category-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "language" character varying NOT NULL, "description" character varying NOT NULL, "diseaseCategoryId" uuid, CONSTRAINT "PK_2fb84f1697807f297ceacfd607d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_4869208a67a4f4c77ab384ff524" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-temp-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "advice" character varying NOT NULL, "dangerElement" character varying NOT NULL, "symptom" character varying NOT NULL, "treatment" character varying NOT NULL, "type" integer NOT NULL, "language" character varying NOT NULL, "diseaseTempId" uuid, CONSTRAINT "PK_2c44b1c93157973e0add3204adb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-temp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "diseaseCategoryId" uuid, CONSTRAINT "PK_df70d9a1311ded677cc8832430d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-disease-report-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "geneSeq" character varying NOT NULL, "phenotype" character varying NOT NULL, "language" character varying NOT NULL, "genotypeDiseaseReportId" uuid, CONSTRAINT "PK_83da27b358630b311c1f11ca09b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-disease-report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "diseaseReportId" uuid, CONSTRAINT "PK_15cba9204c83f4dcb73df24e20e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-report-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "finalConclusion" character varying, "draftConclusion" character varying, "language" character varying NOT NULL, "diseaseReportId" uuid, CONSTRAINT "PK_685cab7d6626d03076d4990670f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "diseaseTempId" uuid, "userId" uuid, CONSTRAINT "PK_ea2d457814f6c83f7a86e3f50c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-drug-temp-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "geneSeq" character varying NOT NULL, "phenotype" character varying NOT NULL, "language" character varying NOT NULL, "genotypeDrugTempId" uuid, CONSTRAINT "PK_f8ecf5ff6bc49a29ef0b302a1e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-drug-temp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "drugTempId" uuid, CONSTRAINT "PK_18093e0e2208a17a45c255dff28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug-category-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "language" character varying NOT NULL, "description" character varying NOT NULL, "drugCategoryId" uuid, CONSTRAINT "PK_50bc51e08a288285038ee2d15b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug-category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_6499e17101e47d101dda717ff92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug-temp-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "advice" character varying NOT NULL, "diseaseTreatment" character varying NOT NULL, "language" character varying NOT NULL, "drugTempId" uuid, CONSTRAINT "PK_69eceb1ec0ff1f995eee680847e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug-temp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "drugCategoryId" uuid, CONSTRAINT "PK_eb879ff65fff1d2da4054d28f65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-drug-report-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "geneSeq" character varying NOT NULL, "phenotype" character varying NOT NULL, "language" character varying NOT NULL, "genotypeDrugReportId" uuid, CONSTRAINT "PK_cd50b8def8143a48d0f7a7ae89d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-drug-report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "drugReportId" uuid, CONSTRAINT "PK_6bc3011d0c603a79e4e9bd738dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug-report-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "finalConclusion" character varying, "draftConclusion" character varying, "language" character varying NOT NULL, "drugReportId" uuid, CONSTRAINT "PK_7502f3434be879a432f2906da80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drug-report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "drugTempId" uuid, "userId" uuid, CONSTRAINT "PK_b09f629e2175deac80519060b2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-nutrition-temp-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "geneSeq" character varying NOT NULL, "phenotype" character varying NOT NULL, "language" character varying NOT NULL, "genotypeNutritionTempId" uuid, CONSTRAINT "PK_1c992f645de3e22adfbf73c51fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-nutrition-temp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "nutritionTempId" uuid, CONSTRAINT "PK_96336e6b544ce4321d57f449c9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition-category-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "language" character varying NOT NULL, "description" character varying NOT NULL, "nutritionCategoryId" uuid, CONSTRAINT "PK_f763950d9917fcbb2d90b66b161" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition-category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_7c81e7dbd24429aa9c70b5ab17d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition-temp-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "advice" character varying NOT NULL, "language" character varying NOT NULL, "nutritionTempId" uuid, CONSTRAINT "PK_61da990281a7acccfd513d996a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition-temp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nutritionCategoryId" uuid, CONSTRAINT "PK_298fd32030cc90b9b894980cf9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-nutrition-report-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "geneSeq" character varying NOT NULL, "phenotype" character varying NOT NULL, "language" character varying NOT NULL, "genotypeNutritionReportId" uuid, CONSTRAINT "PK_48d21af6d0640d5d81933afc804" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genotype-nutrition-report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "nutritionReportId" uuid, CONSTRAINT "PK_1abbb519333b8846ba52586cf8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition-report-trans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "finalConclusion" character varying, "draftConclusion" character varying, "language" character varying NOT NULL, "nutritionReportId" uuid, CONSTRAINT "PK_2723b4a1ae43423505c06752768" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition-report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nutritionTempId" uuid, "userId" uuid, CONSTRAINT "PK_2da9b1a5e68ba99247d21478a90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "birthday" character varying NOT NULL, "gender" character varying NOT NULL, "account" character varying NOT NULL, "password" character varying NOT NULL, "salt" character varying NOT NULL, "role" character varying NOT NULL, CONSTRAINT "UQ_4ab2df0a57a74fdf904e0e27086" UNIQUE ("account"), CONSTRAINT "UQ_4ab2df0a57a74fdf904e0e27086" UNIQUE ("account"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-temp-trans" ADD CONSTRAINT "FK_f7bcf47b6fe2f5a9018b305c282" FOREIGN KEY ("genotypeDiseaseTempId") REFERENCES "genotype-disease-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-temp" ADD CONSTRAINT "FK_a3b393083c24f773f08977b2e88" FOREIGN KEY ("diseaseTempId") REFERENCES "disease-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease-category-trans" ADD CONSTRAINT "FK_a52c6f90395be1e810724610dd6" FOREIGN KEY ("diseaseCategoryId") REFERENCES "disease-category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease-temp-trans" ADD CONSTRAINT "FK_934ad27b629f5d56ba205b9a123" FOREIGN KEY ("diseaseTempId") REFERENCES "disease-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease-temp" ADD CONSTRAINT "FK_5612403fd467b6d65980866950e" FOREIGN KEY ("diseaseCategoryId") REFERENCES "disease-category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-report-trans" ADD CONSTRAINT "FK_1ef4ca617cd23ea54df1b469625" FOREIGN KEY ("genotypeDiseaseReportId") REFERENCES "genotype-disease-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-report" ADD CONSTRAINT "FK_ea202a49a72fea37fd499281ba8" FOREIGN KEY ("diseaseReportId") REFERENCES "disease-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease-report-trans" ADD CONSTRAINT "FK_2e91bbef3ce250ca91cec49b7df" FOREIGN KEY ("diseaseReportId") REFERENCES "disease-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease-report" ADD CONSTRAINT "FK_43ff26030b7160c58fee5bf058e" FOREIGN KEY ("diseaseTempId") REFERENCES "disease-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disease-report" ADD CONSTRAINT "FK_957d29bfd342e0359c70bff64dc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-temp-trans" ADD CONSTRAINT "FK_24f6b10157d1b2f57665d37a76a" FOREIGN KEY ("genotypeDrugTempId") REFERENCES "genotype-drug-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-temp" ADD CONSTRAINT "FK_b8eeed54c537124314265d316f0" FOREIGN KEY ("drugTempId") REFERENCES "drug-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug-category-trans" ADD CONSTRAINT "FK_e95e329043a89a8a9ed9ecb375c" FOREIGN KEY ("drugCategoryId") REFERENCES "drug-category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug-temp-trans" ADD CONSTRAINT "FK_cbf4127f0b4cc4b5024fe1e616f" FOREIGN KEY ("drugTempId") REFERENCES "drug-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug-temp" ADD CONSTRAINT "FK_e88432086e3c0a502eb9d641d9f" FOREIGN KEY ("drugCategoryId") REFERENCES "drug-category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-report-trans" ADD CONSTRAINT "FK_ffa4b9535b1435b4183ddc0b19f" FOREIGN KEY ("genotypeDrugReportId") REFERENCES "genotype-drug-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-report" ADD CONSTRAINT "FK_86e6b7675d440a45886faea9e43" FOREIGN KEY ("drugReportId") REFERENCES "drug-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug-report-trans" ADD CONSTRAINT "FK_67a2e5dde68685f481c4089b1de" FOREIGN KEY ("drugReportId") REFERENCES "drug-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug-report" ADD CONSTRAINT "FK_c42e2b853db69e5aba9014e36c5" FOREIGN KEY ("drugTempId") REFERENCES "drug-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug-report" ADD CONSTRAINT "FK_c17c92e8da2933b2a852573dc2e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-temp-trans" ADD CONSTRAINT "FK_5474f6e9d88f6bb8f9006f22977" FOREIGN KEY ("genotypeNutritionTempId") REFERENCES "genotype-nutrition-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-temp" ADD CONSTRAINT "FK_fe7001389cba2d3d086c5befc83" FOREIGN KEY ("nutritionTempId") REFERENCES "nutrition-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition-category-trans" ADD CONSTRAINT "FK_82ca357e0dd0fb337e691f85e1c" FOREIGN KEY ("nutritionCategoryId") REFERENCES "nutrition-category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition-temp-trans" ADD CONSTRAINT "FK_c43d53a4e72d87104bafc7a28d9" FOREIGN KEY ("nutritionTempId") REFERENCES "nutrition-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition-temp" ADD CONSTRAINT "FK_5d8345517f68964e7422a68fa16" FOREIGN KEY ("nutritionCategoryId") REFERENCES "nutrition-category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-report-trans" ADD CONSTRAINT "FK_c289c4d7ebeed7a17fdd39750f2" FOREIGN KEY ("genotypeNutritionReportId") REFERENCES "genotype-nutrition-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-report" ADD CONSTRAINT "FK_67bdf5b0c679756b653b5ef197f" FOREIGN KEY ("nutritionReportId") REFERENCES "nutrition-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition-report-trans" ADD CONSTRAINT "FK_12966136234975a69ff6432a351" FOREIGN KEY ("nutritionReportId") REFERENCES "nutrition-report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition-report" ADD CONSTRAINT "FK_e240da6677e2d933c2877cb9376" FOREIGN KEY ("nutritionTempId") REFERENCES "nutrition-temp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition-report" ADD CONSTRAINT "FK_b5113502f1b0aca059f23836a72" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nutrition-report" DROP CONSTRAINT "FK_b5113502f1b0aca059f23836a72"`);
        await queryRunner.query(`ALTER TABLE "nutrition-report" DROP CONSTRAINT "FK_e240da6677e2d933c2877cb9376"`);
        await queryRunner.query(`ALTER TABLE "nutrition-report-trans" DROP CONSTRAINT "FK_12966136234975a69ff6432a351"`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-report" DROP CONSTRAINT "FK_67bdf5b0c679756b653b5ef197f"`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-report-trans" DROP CONSTRAINT "FK_c289c4d7ebeed7a17fdd39750f2"`);
        await queryRunner.query(`ALTER TABLE "nutrition-temp" DROP CONSTRAINT "FK_5d8345517f68964e7422a68fa16"`);
        await queryRunner.query(`ALTER TABLE "nutrition-temp-trans" DROP CONSTRAINT "FK_c43d53a4e72d87104bafc7a28d9"`);
        await queryRunner.query(`ALTER TABLE "nutrition-category-trans" DROP CONSTRAINT "FK_82ca357e0dd0fb337e691f85e1c"`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-temp" DROP CONSTRAINT "FK_fe7001389cba2d3d086c5befc83"`);
        await queryRunner.query(`ALTER TABLE "genotype-nutrition-temp-trans" DROP CONSTRAINT "FK_5474f6e9d88f6bb8f9006f22977"`);
        await queryRunner.query(`ALTER TABLE "drug-report" DROP CONSTRAINT "FK_c17c92e8da2933b2a852573dc2e"`);
        await queryRunner.query(`ALTER TABLE "drug-report" DROP CONSTRAINT "FK_c42e2b853db69e5aba9014e36c5"`);
        await queryRunner.query(`ALTER TABLE "drug-report-trans" DROP CONSTRAINT "FK_67a2e5dde68685f481c4089b1de"`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-report" DROP CONSTRAINT "FK_86e6b7675d440a45886faea9e43"`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-report-trans" DROP CONSTRAINT "FK_ffa4b9535b1435b4183ddc0b19f"`);
        await queryRunner.query(`ALTER TABLE "drug-temp" DROP CONSTRAINT "FK_e88432086e3c0a502eb9d641d9f"`);
        await queryRunner.query(`ALTER TABLE "drug-temp-trans" DROP CONSTRAINT "FK_cbf4127f0b4cc4b5024fe1e616f"`);
        await queryRunner.query(`ALTER TABLE "drug-category-trans" DROP CONSTRAINT "FK_e95e329043a89a8a9ed9ecb375c"`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-temp" DROP CONSTRAINT "FK_b8eeed54c537124314265d316f0"`);
        await queryRunner.query(`ALTER TABLE "genotype-drug-temp-trans" DROP CONSTRAINT "FK_24f6b10157d1b2f57665d37a76a"`);
        await queryRunner.query(`ALTER TABLE "disease-report" DROP CONSTRAINT "FK_957d29bfd342e0359c70bff64dc"`);
        await queryRunner.query(`ALTER TABLE "disease-report" DROP CONSTRAINT "FK_43ff26030b7160c58fee5bf058e"`);
        await queryRunner.query(`ALTER TABLE "disease-report-trans" DROP CONSTRAINT "FK_2e91bbef3ce250ca91cec49b7df"`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-report" DROP CONSTRAINT "FK_ea202a49a72fea37fd499281ba8"`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-report-trans" DROP CONSTRAINT "FK_1ef4ca617cd23ea54df1b469625"`);
        await queryRunner.query(`ALTER TABLE "disease-temp" DROP CONSTRAINT "FK_5612403fd467b6d65980866950e"`);
        await queryRunner.query(`ALTER TABLE "disease-temp-trans" DROP CONSTRAINT "FK_934ad27b629f5d56ba205b9a123"`);
        await queryRunner.query(`ALTER TABLE "disease-category-trans" DROP CONSTRAINT "FK_a52c6f90395be1e810724610dd6"`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-temp" DROP CONSTRAINT "FK_a3b393083c24f773f08977b2e88"`);
        await queryRunner.query(`ALTER TABLE "genotype-disease-temp-trans" DROP CONSTRAINT "FK_f7bcf47b6fe2f5a9018b305c282"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "nutrition-report"`);
        await queryRunner.query(`DROP TABLE "nutrition-report-trans"`);
        await queryRunner.query(`DROP TABLE "genotype-nutrition-report"`);
        await queryRunner.query(`DROP TABLE "genotype-nutrition-report-trans"`);
        await queryRunner.query(`DROP TABLE "nutrition-temp"`);
        await queryRunner.query(`DROP TABLE "nutrition-temp-trans"`);
        await queryRunner.query(`DROP TABLE "nutrition-category"`);
        await queryRunner.query(`DROP TABLE "nutrition-category-trans"`);
        await queryRunner.query(`DROP TABLE "genotype-nutrition-temp"`);
        await queryRunner.query(`DROP TABLE "genotype-nutrition-temp-trans"`);
        await queryRunner.query(`DROP TABLE "drug-report"`);
        await queryRunner.query(`DROP TABLE "drug-report-trans"`);
        await queryRunner.query(`DROP TABLE "genotype-drug-report"`);
        await queryRunner.query(`DROP TABLE "genotype-drug-report-trans"`);
        await queryRunner.query(`DROP TABLE "drug-temp"`);
        await queryRunner.query(`DROP TABLE "drug-temp-trans"`);
        await queryRunner.query(`DROP TABLE "drug-category"`);
        await queryRunner.query(`DROP TABLE "drug-category-trans"`);
        await queryRunner.query(`DROP TABLE "genotype-drug-temp"`);
        await queryRunner.query(`DROP TABLE "genotype-drug-temp-trans"`);
        await queryRunner.query(`DROP TABLE "disease-report"`);
        await queryRunner.query(`DROP TABLE "disease-report-trans"`);
        await queryRunner.query(`DROP TABLE "genotype-disease-report"`);
        await queryRunner.query(`DROP TABLE "genotype-disease-report-trans"`);
        await queryRunner.query(`DROP TABLE "disease-temp"`);
        await queryRunner.query(`DROP TABLE "disease-temp-trans"`);
        await queryRunner.query(`DROP TABLE "disease-category"`);
        await queryRunner.query(`DROP TABLE "disease-category-trans"`);
        await queryRunner.query(`DROP TABLE "genotype-disease-temp"`);
        await queryRunner.query(`DROP TABLE "genotype-disease-temp-trans"`);
    }

}
